export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'fun' | 'utility' | 'image' | 'medical';
  href: string;
  popular?: boolean;
}

export const tools: Tool[] = [
  {
    id: 'mbti',
    name: 'MBTI 性格测试',
    description: '16型人格免费测试，了解你的性格类型和职业倾向',
    icon: '🧠',
    category: 'fun',
    href: '/tools/mbti',
    popular: true,
  },
  {
    id: 'love-test',
    name: '恋爱脑测试',
    description: '测测你是不是恋爱脑，朋友圈都在玩的趣味测试',
    icon: '💕',
    category: 'fun',
    href: '/tools/love-test',
    popular: true,
  },
  {
    id: 'lucky',
    name: '幸运数字生成器',
    description: '根据姓名和生日生成你的专属幸运数字和运势',
    icon: '🍀',
    category: 'fun',
    href: '/tools/lucky',
    popular: true,
  },
  {
    id: 'fortune',
    name: '今日运势',
    description: '每日运势预测，事业、爱情、财运一网打尽',
    icon: '🔮',
    category: 'fun',
    href: '/tools/fortune',
  },
  {
    id: 'qrcode',
    name: '二维码生成器',
    description: '免费在线生成二维码，支持自定义颜色和样式',
    icon: '📱',
    category: 'utility',
    href: '/tools/qrcode',
  },
  {
    id: 'image-compress',
    name: '图片压缩工具',
    description: '在线压缩PNG/JPEG图片，减小文件体积不失真',
    icon: '🖼️',
    category: 'image',
    href: '/tools/image-compress',
    popular: true,
  },
  {
    id: 'text-tools',
    name: '文本处理工具',
    description: '字数统计、大小写转换、文本对比等多种文本处理',
    icon: '📝',
    category: 'utility',
    href: '/tools/text-tools',
  },
  {
    id: 'password',
    name: '密码生成器',
    description: '生成高强度随机密码，保护你的账号安全',
    icon: '🔐',
    category: 'utility',
    href: '/tools/password',
  },
  {
    id: 'color-palette',
    name: '配色方案生成器',
    description: '一键生成好看的配色方案，适合设计和开发使用',
    icon: '🎨',
    category: 'utility',
    href: '/tools/color-palette',
  },
  {
    id: 'json',
    name: 'JSON 格式化工具',
    description: 'JSON格式化、压缩、校验，开发者必备工具',
    icon: '🔧',
    category: 'utility',
    href: '/tools/json',
  },
  {
    id: 'meme',
    name: '表情包生成器',
    description: '在线制作搞笑表情包，快速生成分享到朋友圈',
    icon: '😂',
    category: 'fun',
    href: '/tools/meme',
  },
  {
    id: 'name-score',
    name: '姓名打分器',
    description: '输入姓名，看看你的名字能打多少分',
    icon: '⭐',
    category: 'fun',
    href: '/tools/name-score',
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: '在线Unix时间戳和日期互转，支持秒/毫秒精度',
    icon: '⏱️',
    category: 'utility',
    href: '/tools/timestamp',
  },
  {
    id: 'base64',
    name: 'Base64 编解码',
    description: '在线Base64编码解码工具，支持中文和UTF-8',
    icon: '🔣',
    category: 'utility',
    href: '/tools/base64',
  },
  {
    id: 'hash',
    name: '哈希计算器',
    description: 'MD5/SHA256在线加密，支持文本和文件哈希计算',
    icon: '🔒',
    category: 'utility',
    href: '/tools/hash',
  },
  {
    id: 'bmi',
    name: 'BMI 计算器',
    description: '身体质量指数计算，输入身高体重即可了解健康状况',
    icon: '⚖️',
    category: 'medical',
    href: '/tools/bmi',
  },
  {
    id: 'age-calculator',
    name: '年龄计算器',
    description: '精确计算年龄，显示周岁、月份、天数，还能算出生到现在的总天数',
    icon: '📅',
    category: 'fun',
    href: '/tools/age-calculator',
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    description: '在线批量生成UUID，支持v4随机UUID，开发者必备',
    icon: '🆔',
    category: 'utility',
    href: '/tools/uuid',
  },
  {
    id: 'url-encode',
    name: 'URL 编解码',
    description: '在线URL编码解码工具，支持encodeURIComponent和decodeURIComponent',
    icon: '🔗',
    category: 'utility',
    href: '/tools/url-encode',
  },
  {
    id: 'dedup',
    name: '文字去重工具',
    description: '在线文本去重，支持按行去重、忽略空行、保留顺序',
    icon: '📋',
    category: 'utility',
    href: '/tools/dedup',
  },
  {
    id: 'word-count',
    name: '字数统计器',
    description: '在线统计中文字数、英文字符数、行数、段落数，写作辅助必备',
    icon: '📊',
    category: 'utility',
    href: '/tools/word-count',
  },
  {
    id: 'regex',
    name: '正则表达式测试',
    description: '在线正则表达式测试工具，实时匹配高亮，支持常用正则速查',
    icon: '🔍',
    category: 'utility',
    href: '/tools/regex',
  },
  {
    id: 'ip-lookup',
    name: 'IP 地址查询',
    description: '查询你的公网IP地址和基本信息，支持IPv4/IPv6检测',
    icon: '🌐',
    category: 'utility',
    href: '/tools/ip-lookup',
  },
  {
    id: 'hepatitis-b',
    name: '乙肝大小三阳自测',
    description: '根据乙肝五项检测结果快速判定大三阳/小三阳/未感染，健康科普参考',
    icon: '🩺',
    category: 'medical',
    href: '/tools/hepatitis-b',
  },
  {
    id: 'hepatitis-b-treatment',
    name: '乙肝是否需要抗病毒治疗',
    description: '根据HBsAg和HBV DNA检测结果判定是否需要抗病毒治疗，健康科普参考',
    icon: '💊',
    category: 'medical',
    href: '/tools/hepatitis-b-treatment',
  },
  {
    id: 'novel-to-video',
    name: '小说配图转视频',
    description: '将小说自动生成动漫配图并合成视频，AI文生图免费使用',
    icon: '📖',
    category: 'utility',
    href: '/tools/novel-to-video',
    popular: true,
  },
  {
    id: 'lung-cancer',
    name: '肺癌治疗方案速查',
    description: '基于指南的肺癌综合治疗方案查询，按分期/基因/体能推荐NSCLC和SCLC方案',
    icon: '🫁',
    category: 'medical',
    href: '/tools/lung-cancer',
  },
  {
    id: 'hypertension-risk',
    name: '高血压风险评估',
    description: '输入血压/年龄/BMI/家族史/吸烟等指标，评估高血压风险等级',
    icon: '🫀',
    category: 'medical',
    href: '/tools/hypertension-risk',
  },
  {
    id: 'diabetes-risk',
    name: '糖尿病风险评估',
    description: '基于中国糖尿病风险评分表，输入年龄/腰围/家族史等指标评估患病风险',
    icon: '🩸',
    category: 'medical',
    href: '/tools/diabetes-risk',
  },
  {
    id: 'stroke-risk',
    name: '中风风险评估',
    description: '基于改良Framingham卒中风险评分，评估10年卒中风险',
    icon: '🧠',
    category: 'medical',
    href: '/tools/stroke-risk',
  },
  {
    id: 'gout-risk',
    name: '痛风风险评估',
    description: '输入尿酸值、关节症状、饮食史，评估痛风和发作风险等级',
    icon: '🦶',
    category: 'medical',
    href: '/tools/gout-risk',
  },
  {
    id: 'egfr',
    name: 'eGFR 肾小球滤过率计算',
    description: '基于CKD-EPI公式，输入肌酐/年龄/性别计算肾小球滤过率，评估肾功能',
    icon: '🫘',
    category: 'medical',
    href: '/tools/egfr',
  },
  {
    id: 'bsa',
    name: '体表面积 BSA 计算',
    description: '支持Mosteller/DuBois等多种公式，化疗药物剂量和心输出量计算必备',
    icon: '📐',
    category: 'medical',
    href: '/tools/bsa',
  },
  {
    id: 'due-date',
    name: '预产期计算器',
    description: '末次月经推算预产期，显示当前孕周、距离预产期天数，孕期必备',
    icon: '👶',
    category: 'medical',
    href: '/tools/due-date',
  },
  {
    id: 'cha2ds2-vasc',
    name: 'CHA₂DS₂-VASc 卒中评分',
    description: '房颤患者卒中风险评估工具，指导是否需要抗凝治疗',
    icon: '💓',
    category: 'medical',
    href: '/tools/cha2ds2-vasc',
  },
  {
    id: 'wells-score',
    name: 'Wells 肺栓塞评分',
    description: '深静脉血栓和肺栓塞临床概率评估，辅助D二聚体检测决策',
    icon: '🫧',
    category: 'medical',
    href: '/tools/wells-score',
  },
  {
    id: 'headache-check',
    name: '头痛鉴别',
    description: '偏头痛/紧张性/丛集性头痛鉴别，含危险信号筛查，健康科普参考',
    icon: '🤕',
    category: 'medical',
    href: '/tools/headache-check',
  },
  {
    id: 'chest-pain-check',
    name: '胸痛鉴别',
    description: '心源性/肺源性/消化性/肌肉性胸痛初步鉴别，含紧急就医提示',
    icon: '💔',
    category: 'medical',
    href: '/tools/chest-pain-check',
  },
  {
    id: 'abdominal-pain-check',
    name: '腹痛鉴别',
    description: '按疼痛部位和性质区分腹痛原因，急腹症警示，健康科普参考',
    icon: '🔽',
    category: 'medical',
    href: '/tools/abdominal-pain-check',
  },
  {
    id: 'rash-check',
    name: '皮疹鉴别',
    description: '按皮疹形态分类鉴别，传染性/过敏性/自身免疫性皮疹特征对比',
    icon: '🔴',
    category: 'medical',
    href: '/tools/rash-check',
  },
  {
    id: 'eq-test',
    name: '情商测试 (EQ Test)',
    description: '基于戈尔曼情商模型，5大维度20道情景题评估你的情商水平',
    icon: '🧘',
    category: 'fun',
    href: '/tools/eq-test',
  },
  {
    id: 'aq-test',
    name: '逆商测试 (AQ Test)',
    description: '基于保罗·史托兹逆商理论，C.O.R.E四维模型20道情景题评估你的逆境应对能力',
    icon: '🏔️',
    category: 'fun',
    href: '/tools/aq-test',
  },
  {
    id: 'adult-iq-test',
    name: '成人智商测试 (IQ Test)',
    description: '涵盖逻辑、数学、语言、空间和抽象思维5个维度的认知能力评估',
    icon: '🧠',
    category: 'fun',
    href: '/tools/adult-iq-test',
  },
  {
    id: 'child-iq-test',
    name: '儿童智商测试',
    description: '适用于6-16岁儿童的趣味智力测评，多维度评估逻辑、数学、语言等能力',
    icon: '🧒',
    category: 'fun',
    href: '/tools/child-iq-test',
  },
  {
    id: 'liver-cancer-staging',
    name: '肝癌CNLC分期自测',
    description: '基于《原发性肝癌诊疗指南》CNLC分期系统，输入临床指标获取分期和治疗建议',
    icon: '🏥',
    category: 'medical',
    href: '/tools/liver-cancer-staging',
  },
  {
    id: 'bazi',
    name: '四柱预测',
    description: '免费在线四柱八字测算，根据出生年月日时推算命理格局、五行分布',
    icon: '🎱',
    category: 'fun',
    href: '/tools/bazi',
    popular: true,
  },
  {
    id: 'image-convert',
    name: '图片格式转换',
    description: 'PNG/JPG/WebP在线互转，纯浏览器端处理，支持批量转换',
    icon: '🔄',
    category: 'image',
    href: '/tools/image-convert',
    popular: true,
  },
  {
    id: 'gif-maker',
    name: 'GIF 制作器',
    description: '多张图片合成动态GIF，支持帧排序、自定义速度和尺寸',
    icon: '🎬',
    category: 'image',
    href: '/tools/gif-maker',
    popular: true,
  },
  {
    id: 'qr-decode',
    name: '二维码解码器',
    description: '上传二维码图片或使用摄像头扫描，快速识别二维码内容',
    icon: '📷',
    category: 'utility',
    href: '/tools/qr-decode',
  },
  {
    id: 'text-diff',
    name: '文本差异对比',
    description: '两段文本逐行对比差异高亮，支持统一视图和并排对比',
    icon: '📊',
    category: 'utility',
    href: '/tools/text-diff',
  },
  {
    id: 'crontab',
    name: 'Crontab 表达式生成器',
    description: '可视化配置Cron定时任务，支持预设、含义解读和执行时间计算',
    icon: '⏰',
    category: 'utility',
    href: '/tools/crontab',
  },
];

export const categoryLabels: Record<string, string> = {
  fun: '趣味测试',
  utility: '实用工具',
  image: '图片处理',
  medical: '医学工具',
};

export const categoryIcons: Record<string, string> = {
  fun: '🎯',
  utility: '🛠️',
  image: '🖼️',
  medical: '🏥',
};
